services:
  aas-environment:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080

      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"

      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: "http://aas-registry:8080"
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: "http://submodel-registry:8080"

      BASYX_ENVIRONMENT: file:/application/aas
      BASYX_EXTERNALURL: "http://localhost:8081"
    volumes:
      - ./aas:/application/aas
    depends_on:
      aas-registry:
        condition: service_healthy
      submodel-registry:
        condition: service_healthy

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080

      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"

  submodel-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080

      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"

  aas-gui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    ports:
      - "3000:3000"
    environment:
      AAS_REPO_PATH: "http://localhost:8081/shells"
      SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"
      AAS_REGISTRY_PATH: "http://localhost:8082/shell-descriptors"
      SUBMODEL_REGISTRY_PATH: "http://localhost:8083/submodel-descriptors"
    depends_on:
      aas-environment:
        condition: service_healthy
